name: Compile TypeScript

on:
  push:
  pull_request:

jobs:
  tsc:
    name: Compile TypeScript
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Current Repository
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Node Modules
        run: npm ci

      - name: Compile TypeScript
        uses: icrawl/action-tsc@v1
